// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: test/test.proto

package test

import (
	protox "github.com/cloudfly/protox"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error int32

const (
	Error_InternalServerError Error = 0
	Error_PermissionDenied    Error = 1
	Error_NotFound            Error = 2
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0: "InternalServerError",
		1: "PermissionDenied",
		2: "NotFound",
	}
	Error_value = map[string]int32{
		"InternalServerError": 0,
		"PermissionDenied":    1,
		"NotFound":            2,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_test_test_proto_enumTypes[0].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_test_test_proto_enumTypes[0]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_test_test_proto_rawDescGZIP(), []int{0}
}

type TestCommon struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Public *string                `protobuf:"bytes,3,opt,name=Public,proto3,oneof" json:"Public,omitempty"`
	// @gotags: db:"-" json:"id"
	PublicId string `protobuf:"bytes,5,opt,name=publicId,proto3" json:"publicId,omitempty"`
	// @gotags: db:"type"
	Type string `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"` // 'enum' | 'message'
	// @gotags: db:"description"
	Description string `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	// @gotags: db:"fields"
	ProjectId int64 `protobuf:"varint,11,opt,name=projectId,proto3" json:"projectId,omitempty"`
	// @gotags: db:"createTime"
	CreateTime *protox.Timestamp `protobuf:"bytes,12,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// @gotags: db:"updateTime"
	UpdateTime    *protox.Timestamp `protobuf:"bytes,13,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCommon) Reset() {
	*x = TestCommon{}
	mi := &file_test_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCommon) ProtoMessage() {}

func (x *TestCommon) ProtoReflect() protoreflect.Message {
	mi := &file_test_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCommon.ProtoReflect.Descriptor instead.
func (*TestCommon) Descriptor() ([]byte, []int) {
	return file_test_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestCommon) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TestCommon) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TestCommon) GetPublic() string {
	if x != nil && x.Public != nil {
		return *x.Public
	}
	return ""
}

func (x *TestCommon) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *TestCommon) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TestCommon) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TestCommon) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *TestCommon) GetCreateTime() *protox.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *TestCommon) GetUpdateTime() *protox.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type TestOrmx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestOrmx) Reset() {
	*x = TestOrmx{}
	mi := &file_test_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestOrmx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestOrmx) ProtoMessage() {}

func (x *TestOrmx) ProtoReflect() protoreflect.Message {
	mi := &file_test_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestOrmx.ProtoReflect.Descriptor instead.
func (*TestOrmx) Descriptor() ([]byte, []int) {
	return file_test_test_proto_rawDescGZIP(), []int{1}
}

func (x *TestOrmx) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TestOrmx) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_test_test_proto protoreflect.FileDescriptor

const file_test_test_proto_rawDesc = "" +
	"\n" +
	"\x0ftest/test.proto\x12\x04test\x1a\fprotox.proto\"\x8a\x03\n" +
	"\n" +
	"TestCommon\x12\x15\n" +
	"\x02id\x18\x01 \x01(\x03B\x05\xb2\xc3&\x01-R\x02id\x12*\n" +
	"\x04name\x18\x02 \x01(\tB\x11\xb2\xc3&\rNAME,readonlyH\x00R\x04name\x88\x01\x01\x122\n" +
	"\x06Public\x18\x03 \x01(\tB\x15\xb2\xc3&\x11_public,writeonlyH\x01R\x06Public\x88\x01\x01\x12\x1a\n" +
	"\bpublicId\x18\x05 \x01(\tR\bpublicId\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1c\n" +
	"\tprojectId\x18\v \x01(\x03R\tprojectId\x121\n" +
	"\n" +
	"createTime\x18\f \x01(\v2\x11.protox.TimestampR\n" +
	"createTime\x121\n" +
	"\n" +
	"updateTime\x18\r \x01(\v2\x11.protox.TimestampR\n" +
	"updateTime:\x1b\xaa\xc3&\r\n" +
	"\x05Table\x12\x04Test\xb2\xc3&\x06\x12\x04jsonB\a\n" +
	"\x05_nameB\t\n" +
	"\a_Public\"^\n" +
	"\bTestOrmx\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x03B\x0e\xba\xc3&\n" +
	"\xaa\xc3&\x02id\xb0\xc3&\x01R\x02id\x122\n" +
	"\x04name\x18\x02 \x01(\tB\x1e\xba\xc3&\x1a\xaa\xc3&\x04name\xb0\xc3&\x01\xb8\xc3&\x01\xc0\xc3&\x00\xfa\xc3&\x02eqR\x04name*\x85\x01\n" +
	"\x05Error\x122\n" +
	"\x13InternalServerError\x10\x00\x1a\x19\xba\xc3&\x15internal_server_error\x12+\n" +
	"\x10PermissionDenied\x10\x01\x1a\x15\xba\xc3&\x11permission_denied\x12\x1b\n" +
	"\bNotFound\x10\x02\x1a\r\xba\xc3&\tnot_foundB!Z\x1fgithub.com/cloudfly/protox/testb\x06proto3"

var (
	file_test_test_proto_rawDescOnce sync.Once
	file_test_test_proto_rawDescData []byte
)

func file_test_test_proto_rawDescGZIP() []byte {
	file_test_test_proto_rawDescOnce.Do(func() {
		file_test_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_test_proto_rawDesc), len(file_test_test_proto_rawDesc)))
	})
	return file_test_test_proto_rawDescData
}

var file_test_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_test_proto_goTypes = []any{
	(Error)(0),               // 0: test.Error
	(*TestCommon)(nil),       // 1: test.TestCommon
	(*TestOrmx)(nil),         // 2: test.TestOrmx
	(*protox.Timestamp)(nil), // 3: protox.Timestamp
}
var file_test_test_proto_depIdxs = []int32{
	3, // 0: test.TestCommon.createTime:type_name -> protox.Timestamp
	3, // 1: test.TestCommon.updateTime:type_name -> protox.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_test_test_proto_init() }
func file_test_test_proto_init() {
	if File_test_test_proto != nil {
		return
	}
	file_test_test_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_test_proto_rawDesc), len(file_test_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_test_proto_goTypes,
		DependencyIndexes: file_test_test_proto_depIdxs,
		EnumInfos:         file_test_test_proto_enumTypes,
		MessageInfos:      file_test_test_proto_msgTypes,
	}.Build()
	File_test_test_proto = out.File
	file_test_test_proto_goTypes = nil
	file_test_test_proto_depIdxs = nil
}
