syntax = "proto3";

package test;

option go_package = "github.com/cloudfly/protox/test";

import "protox.proto";

message TestCommon {
  int64 id = 1 [(protox.gojson) = '-'];

  optional string name   = 2 [(protox.gojson) = "NAME,readonly"];
  optional string Public = 3 [(protox.gojson) = "_public,writeonly"];

  // @gotags: db:"-" json:"id"
  string publicId = 5;
  // @gotags: db:"type"
  string type = 8; // 'enum' | 'message'
  // @gotags: db:"description"
  string description = 9;
  // @gotags: db:"fields"
  int64 projectId = 11;
  // @gotags: db:"createTime"
  protox.Timestamp createTime = 12;
  // @gotags: db:"updateTime"
  protox.Timestamp updateTime = 13;

  option (protox.gosql) = {
    serializer: "json"
  };
  option (protox.gomethod) = {
    name  : "Table",
    return: "Test"
  };
}

message TestOrmx {
  int64 id = 1 [
    (protox.ormx).column = "id",
    (protox.ormx).insert = true
  ];

  string name = 2 [
    (protox.ormx) = {
      column: "name",
      insert: true,
      select: true,
      update: false,
      operate: "eq",
    }
  ];

  string noop = 3;
}


enum Error {
	InternalServerError = 0 [(protox.goerror) = "internal_server_error"];
	PermissionDenied = 1 [(protox.goerror) = "permission_denied"];
	NotFound = 2 [(protox.goerror) = "not_found"];
}