// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: test/test.proto

package test

import (
	protox "github.com/cloudfly/protox"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestTest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Public *string                `protobuf:"bytes,3,opt,name=Public,proto3,oneof" json:"Public,omitempty"`
	// @gotags: db:"-" json:"id"
	PublicId string `protobuf:"bytes,5,opt,name=publicId,proto3" json:"publicId,omitempty"`
	// @gotags: db:"type"
	Type string `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"` // 'enum' | 'message'
	// @gotags: db:"description"
	Description string `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	// @gotags: db:"fields"
	ProjectId int64 `protobuf:"varint,11,opt,name=projectId,proto3" json:"projectId,omitempty"`
	// @gotags: db:"createTime"
	CreateTime *protox.Timestamp `protobuf:"bytes,12,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// @gotags: db:"updateTime"
	UpdateTime    *protox.Timestamp `protobuf:"bytes,13,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestTest) Reset() {
	*x = TestTest{}
	mi := &file_test_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTest) ProtoMessage() {}

func (x *TestTest) ProtoReflect() protoreflect.Message {
	mi := &file_test_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTest.ProtoReflect.Descriptor instead.
func (*TestTest) Descriptor() ([]byte, []int) {
	return file_test_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestTest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TestTest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TestTest) GetPublic() string {
	if x != nil && x.Public != nil {
		return *x.Public
	}
	return ""
}

func (x *TestTest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *TestTest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TestTest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TestTest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *TestTest) GetCreateTime() *protox.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *TestTest) GetUpdateTime() *protox.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

var File_test_test_proto protoreflect.FileDescriptor

const file_test_test_proto_rawDesc = "" +
	"\n" +
	"\x0ftest/test.proto\x12\x04test\x1a\fprotox.proto\"\x88\x03\n" +
	"\bTestTest\x12\x15\n" +
	"\x02id\x18\x01 \x01(\x03B\x05\xb2\xc3&\x01-R\x02id\x12*\n" +
	"\x04name\x18\x02 \x01(\tB\x11\xb2\xc3&\rNAME,readonlyH\x00R\x04name\x88\x01\x01\x122\n" +
	"\x06Public\x18\x03 \x01(\tB\x15\xb2\xc3&\x11_public,writeonlyH\x01R\x06Public\x88\x01\x01\x12\x1a\n" +
	"\bpublicId\x18\x05 \x01(\tR\bpublicId\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1c\n" +
	"\tprojectId\x18\v \x01(\x03R\tprojectId\x121\n" +
	"\n" +
	"createTime\x18\f \x01(\v2\x11.protox.TimestampR\n" +
	"createTime\x121\n" +
	"\n" +
	"updateTime\x18\r \x01(\v2\x11.protox.TimestampR\n" +
	"updateTime:\x1b\xaa\xc3&\r\n" +
	"\x05Table\x12\x04Test\xb2\xc3&\x06\x12\x04jsonB\a\n" +
	"\x05_nameB\t\n" +
	"\a_PublicB!Z\x1fgithub.com/cloudfly/protox/testb\x06proto3"

var (
	file_test_test_proto_rawDescOnce sync.Once
	file_test_test_proto_rawDescData []byte
)

func file_test_test_proto_rawDescGZIP() []byte {
	file_test_test_proto_rawDescOnce.Do(func() {
		file_test_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_test_proto_rawDesc), len(file_test_test_proto_rawDesc)))
	})
	return file_test_test_proto_rawDescData
}

var file_test_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_test_proto_goTypes = []any{
	(*TestTest)(nil),         // 0: test.TestTest
	(*protox.Timestamp)(nil), // 1: protox.Timestamp
}
var file_test_test_proto_depIdxs = []int32{
	1, // 0: test.TestTest.createTime:type_name -> protox.Timestamp
	1, // 1: test.TestTest.updateTime:type_name -> protox.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_test_test_proto_init() }
func file_test_test_proto_init() {
	if File_test_test_proto != nil {
		return
	}
	file_test_test_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_test_proto_rawDesc), len(file_test_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_test_proto_goTypes,
		DependencyIndexes: file_test_test_proto_depIdxs,
		MessageInfos:      file_test_test_proto_msgTypes,
	}.Build()
	File_test_test_proto = out.File
	file_test_test_proto_goTypes = nil
	file_test_test_proto_depIdxs = nil
}
