package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"path"
	"slices"
	"strings"
	"unsafe"

	"github.com/cloudfly/protox"
	"github.com/k0kubun/pp"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	gengo "google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

var _ = pp.Println

func init() {
	log.Logger = log.Logger.With().Caller().Logger().Output(&zerolog.ConsoleWriter{Out: os.Stderr})
}

var (
	flags    = flag.NewFlagSet("protox", flag.ContinueOnError)
	outDir   = flags.String("out", ".", "the output directory")
	genProto = flags.String("gen-proto", "", "generate the proto files")
)

var (
	plugin *protogen.Plugin
)

func main() {

	protogen.Options{ParamFunc: flags.Set}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = gengo.SupportedFeatures
		plugin = gen

		for filename, f := range gen.FilesByPath {
			if shouldGenerate(f) {
				gendFile := gengo.GenerateFile(gen, f)
				// skip the file, so that this file will be ignored in Response and no related .pb.go file will be generated,
				// Therefore the generateGoTag() will generate .pb.go file instead.
				gendFile.Skip()

				var err error
				if *genProto != "" {
					log.Info().Str("root", *outDir).Str("file", filename).Msg("Generating extend proto files...")
					err = generateProtos(f)
				} else {
					err = generateGos(filename, gendFile, f)
				}
				if err != nil {
					return err
				}
			}
		}
		return nil
	})
}

func shouldGenerate(f *protogen.File) bool {
	if !f.Generate {
		return false
	}
	/*
		if f.GoImportPath == "github.com/cloudfly/protox" {
			// ignore the protox.proto
			return false
		}
	*/
	if strings.HasPrefix(string(f.GoImportPath), "google.golang.org") {
		return false
	}
	return true
}

func generateProtos(f *protogen.File) error {

	hasApiMessage := false
	for _, m := range f.Messages {
		if opt, _ := m.Desc.Options().(*descriptorpb.MessageOptions); opt != nil {
			if proto.HasExtension(opt, protox.E_Api) {
				hasApiMessage = true
				break
			}
		}
	}

	if !hasApiMessage {
		return nil
	}

	targetProtoFile := fmt.Sprintf("%s.api.proto", strings.TrimSuffix(f.Proto.GetName(), ".proto"))
	targetProtoFile = path.Join(*outDir, targetProtoFile)
	if err := os.MkdirAll(path.Dir(targetProtoFile), 0755); err != nil {
		return err
	}
	log.Info().Str("target", targetProtoFile).Msg("Generating new .proto files...")
	w, err := os.Create(targetProtoFile)
	if err != nil {
		return fmt.Errorf("create file %s error: %w", targetProtoFile, err)
	}
	defer w.Close()

	genWritelnln(w, `
// Code generated by protox. DO NOT EDIT.
syntax = "proto3";

package %s;

import "google/protobuf/empty.proto";
import "utils.proto";
import "protox.proto";
import "%s";`, f.Proto.GetPackage(), path.Base(f.Proto.GetName()))

	for _, m := range f.Messages {
		if opt, _ := m.Desc.Options().(*descriptorpb.MessageOptions); opt != nil {
			if proto.HasExtension(opt, protox.E_Api) {
				if err := generateApiProto(w, f, m, proto.GetExtension(opt, protox.E_Api).(*protox.ApiOption)); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func generateGos(filename string, gendFile *protogen.GeneratedFile, f *protogen.File) error {
	px, err := newPxFile(filename, string(f.GoPackageName))
	if err != nil {
		return err
	}
	defer px.Close()

	log.Info().Str("file", filename).Bool("generate", f.Generate).Msg("Generating go tags ...")
	content, err := gendFile.Content()
	if err != nil {
		return err
	}
	if err := generateGoTag(px, f, content); err != nil {
		return err
	}
	log.Info().Str("file", filename).Msg("Completed generating .pb.go file")

	if err := handleFile(px, f); err != nil {
		return err
	}
	log.Info().Str("file", filename).Msg("Completed handling .px.go file ...")
	return nil
}

func handleFile(px *pxFile, f *protogen.File) error {
	for _, message := range f.Messages {
		if err := handleMessage(px, f, message); err != nil {
			return err
		}
	}
	for _, enum := range f.Enums {
		if err := handleEnum(px, f, enum); err != nil {
			return err
		}
	}
	return nil
}

func handleEnum(px *pxFile, f *protogen.File, e *protogen.Enum) error {
	if err := generateGoError(px, e); err != nil {
		return err
	}
	return nil
}

func handleMessage(px *pxFile, f *protogen.File, m *protogen.Message) error {
	if opt, _ := m.Desc.Options().(*descriptorpb.MessageOptions); opt != nil {
		if proto.HasExtension(opt, protox.E_Method) {
			if err := generateGoMethods(px, m, proto.GetExtension(opt, protox.E_Method)); err != nil {
				return err
			}
		}
		if proto.HasExtension(opt, protox.E_Sql) {
			if err := generateSerializer(px, m, proto.GetExtension(opt, protox.E_Sql)); err != nil {
				return err
			}
		}
		/*
			if proto.HasExtension(opt, protox.E_Inherit) {
				if err := generateGoInherit(px, gen, f, m, proto.GetExtension(opt, protox.E_Inherit)); err != nil {
					return err
				}
			}
		*/
	}

	if err := generateGoJSONMarshaler(px, m); err != nil {
		return err
	}

	return nil
}

func generateSerializer(px *pxFile, m *protogen.Message, value any) error {
	spec := value.(*protox.SQLOption)
	if spec.Serializer == nil {
		return nil
	}
	switch strings.ToLower(*spec.Serializer) {
	case "json":
		return generateSerializerJSON(px, m)
	}
	return nil
}

func generateSerializerJSON(px *pxFile, m *protogen.Message) error {
	px.Import("database/sql/driver", "encoding/json")
	name := m.GoIdent.GoName
	genWriteln(px, "")
	genWriteln(px, "func (data *%s) Scan(src any) error {", name)
	genWritelnIndent(px, 1, `*data = %s{}
	if src == nil {
		return nil
	}
	var content []byte
	switch value := src.(type) {
	case string:
		content = []byte(value)
	case []byte:
		content = value
	default:
		return fmt.Errorf("can not convert %%#v into %s", src)
	}
	if len(content) == 0 {
		return nil
	}
	return json.Unmarshal(content, data)`, name, name)
	genWritelnln(px, "}")

	genWriteln(px, "func (data %s) Value() (driver.Value, error) {", name)
	genWritelnIndent(px, 1, `content, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return string(content), nil`)
	genWritelnln(px, "}")

	return nil
}

func pretty(v ...interface{}) {
	pp.Fprintln(os.Stderr, v...)
}

type pxFile struct {
	started   bool
	imports   []string
	goPackage string
	buf       *bytes.Buffer
	*os.File
}

func newPxFile(filename string, goPackage string) (*pxFile, error) {
	filename = path.Join(*outDir, strings.ReplaceAll(filename, ".proto", ".px.go"))
	if err := os.MkdirAll(path.Dir(filename), 0755); err != nil {
		return nil, err
	}
	px, err := os.Create(filename)
	if err != nil {
		return nil, err
	}
	return &pxFile{
		goPackage: goPackage,
		buf:       &bytes.Buffer{},
		File:      px,
	}, nil
}

func (f *pxFile) Write(data []byte) (n int, err error) {
	if !f.started {
		if _, err = f.File.WriteString("package " + f.goPackage + "\n\n"); err != nil {
			return
		}

		f.started = true
	}

	return f.buf.Write(data)
}

func (f *pxFile) WriteString(s string) (n int, err error) {
	b := unsafe.Slice(unsafe.StringData(s), len(s))
	return f.Write(b)
}

func (f *pxFile) Close() error {

	genImport(f.File, f.imports...)

	if _, err := io.Copy(f.File, f.buf); err != nil {
		return err
	}
	f.buf.Reset()
	f.imports = nil

	if err := f.File.Close(); err != nil {
		return err
	}
	if !f.started {
		return os.Remove(f.File.Name())
	}
	return nil
}

func (f *pxFile) Import(imports ...string) {
	for _, item := range imports {
		if !slices.Contains(f.imports, item) {
			f.imports = append(f.imports, item)
		}
	}
}

func (f *pxFile) Writeln(format string, args ...any) {
	genWriteln(f, format, args...)
}

func (f *pxFile) WritelnIndent(indent int, format string, args ...any) {
	genWritelnIndent(f, indent, format, args...)
}

type JSONOption struct {
	Name      string
	ReadOnly  bool
	WriteOnly bool
}
