package main

import (
	"fmt"
	"io"
	"os"
	"path"
	"slices"
	"strings"

	"github.com/cloudfly/protox"
	"github.com/rs/zerolog/log"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

func generateApiProto(f *protogen.File, m *protogen.Message, options *protox.ApiOption) error {
	targetProtoFile := fmt.Sprintf("%s.api.proto", strings.TrimSuffix(f.Proto.GetName(), ".proto"))
	targetProtoFile = path.Join(*rootDir, targetProtoFile)
	log.Info().Str("target", targetProtoFile).Msg("Generating new .proto files...")
	w, err := os.Create(targetProtoFile)
	if err != nil {
		return fmt.Errorf("create file %s error: %w", targetProtoFile, err)
	}
	defer w.Close()

	genWritelnln(w, `
// Code generated by protox. DO NOT EDIT.
syntax = "proto3";

package %s;

import "google/protobuf/empty.proto";
import "utils.proto";
import "protox.proto";
import "%s";`, f.Proto.GetPackage(), path.Base(f.Proto.GetName()))

	if !options.NoGet {
		if err := generateGetRequest(w, m); err != nil {
			return err
		}
	}
	if !options.NoCreate {
		if err := generateCreateRequest(w, m); err != nil {
			return err
		}
	}
	if !options.NoUpdate {
		if err := generateUpdateRequest(w, m); err != nil {
			return err
		}
	}
	if !options.NoSelect {
		if err := generateSelectRequest(w, f, m); err != nil {
			return err
		}
	}
	if !options.NoDelete {
		if err := generateDeleteRequest(w, m); err != nil {
			return err
		}
	}

	if err := generateService(w, f, m); err != nil {
		return err
	}

	return nil
}

func getFieldClass(field *protogen.Field, prefix string) []string {
	var classes []string
	if opt, _ := field.Desc.Options().(*descriptorpb.FieldOptions); opt != nil {
		if proto.HasExtension(opt, protox.E_Class) {
			classes = strings.Fields(proto.GetExtension(opt, protox.E_Class).(string))
		}
	}

	k := 0
	for _, item := range classes {
		if strings.HasPrefix(item, prefix) {
			classes[k] = strings.TrimPrefix(item, prefix)
			k++
		}
	}
	classes = classes[:k]
	options := make([]string, 0, len(classes))
	for _, class := range classes {
		options = append(options, strings.Split(class, ",")...)
	}
	return options
}

func generateCreateRequest(w io.Writer, m *protogen.Message) error {
	genWriteln(w, "message Create%sRequest {", m.Desc.Name())
	defer genWritelnln(w, "}")

	genWritelnIndent(w, 1, `optional utils.Base Base = 100 [(protox.tag) = 'json:",inline" bson:",inline"'];`)

	for _, field := range m.Fields {
		classes := getFieldClass(field, "create:")
		if len(classes) == 0 {
			continue
		}
		genWritelnIndent(w, 1, "%s %s = %d;",
			fieldProtoType(field.Desc, !slices.Contains(classes, "required")),
			field.Desc.Name(),
			field.Desc.Index(),
		)
	}

	return nil
}

func generateUpdateRequest(w io.Writer, m *protogen.Message) error {
	genWriteln(w, "message Update%sRequest {", m.Desc.Name())
	defer genWritelnln(w, "}")

	genWritelnIndent(w, 1, `optional utils.Base Base = 100 [(protox.tag) = 'json:",inline" bson:",inline"'];`)
	genWritelnIndent(w, 1, "string id = 1;")

	for _, field := range m.Fields {
		classes := getFieldClass(field, "patch:")
		if len(classes) == 0 {
			continue
		}
		genWritelnIndent(w, 1, "%s %s = %d;",
			fieldProtoType(field.Desc, !slices.Contains(classes, "required")),
			field.Desc.Name(),
			field.Desc.Index(),
		)
	}

	return nil
}

func generateSelectRequest(w io.Writer, f *protogen.File, m *protogen.Message) error {
	genWriteln(w, "message List%sRequest {", m.Desc.Name())
	for _, field := range m.Fields {
		classes := getFieldClass(field, "filter:")
		if len(classes) == 0 {
			continue
		}
		genWritelnIndent(w, 1, "%s %s = %d;",
			fieldProtoType(field.Desc, !slices.Contains(classes, "required")),
			field.Desc.Name(),
			field.Desc.Index(),
		)
	}
	genWritelnln(w, "}")

	genWriteln(w, "message List%sResponse {", m.Desc.Name())
	genWritelnIndent(w, 1, "repeated %s.%s items = 1;", f.Proto.GetPackage(), m.Desc.Name())
	genWritelnIndent(w, 1, "int64 total = 2;")
	genWritelnln(w, "}")

	return nil
}

func generateGetRequest(w io.Writer, m *protogen.Message) error {
	genWriteln(w, "message Get%sRequest {", m.Desc.Name())
	defer genWritelnln(w, "}")

	genWritelnIndent(w, 1, "string id = 1;")
	return nil
}

func generateDeleteRequest(w io.Writer, m *protogen.Message) error {
	genWriteln(w, "message Delete%sRequest {", m.Desc.Name())
	defer genWritelnln(w, "}")

	genWritelnIndent(w, 1, "string id = 1;")
	return nil
}

func generateService(w io.Writer, f *protogen.File, m *protogen.Message) error {
	messageName := m.Desc.Name()
	genWriteln(w, "service %sGeneratedApiService {", messageName)
	defer genWriteln(w, "}")

	genWritelnIndent(w, 1, "rpc Create%s(Create%sRequest) returns (%s.%s);", messageName, messageName, f.Proto.GetPackage(), messageName)
	genWritelnIndent(w, 1, "rpc List%s(List%sRequest) returns (List%sResponse);", messageName, messageName, messageName)
	genWritelnIndent(w, 1, "rpc Get%s(Get%sRequest) returns (%s.%s);", messageName, messageName, f.Proto.GetPackage(), messageName)
	genWritelnIndent(w, 1, "rpc Update%s(Update%sRequest) returns (google.protobuf.Empty);", messageName, messageName)
	genWritelnIndent(w, 1, "rpc Delete%s(Delete%sRequest) returns (google.protobuf.Empty);", messageName, messageName)

	return nil
}

func fieldProtoType(field protoreflect.FieldDescriptor, optional bool) string {
	prefix := ""
	if field.IsList() {
		prefix = "repeated "
	} else if field.IsMap() {
		prefix = fmt.Sprintf("map<%s, %s> ", fieldProtoType(field.MapKey(), false), fieldProtoType(field.MapValue(), false))
	} else if optional {
		prefix = "optional "
	}

	if msg := field.Message(); msg != nil {
		return prefix + string(msg.FullName())
	}
	return prefix + field.Kind().String()
}
