syntax="proto3";

package protox;

option go_package = "github.com/cloudfly/protox";

import "google/protobuf/descriptor.proto";

message Timestamp {
	uint32 seconds = 1;
	uint32 nanos = 2;
}

message GoMethodOption {
	string name = 1 [targets = TARGET_TYPE_MESSAGE];
	optional string returnString = 2 [targets = TARGET_TYPE_MESSAGE];
	optional int64 returnInt64 = 3 [targets = TARGET_TYPE_MESSAGE];
	optional bool returnBool = 4 [targets = TARGET_TYPE_MESSAGE];
}

message SQLOption {
	optional string serializer = 2 [targets = TARGET_TYPE_MESSAGE];
}

extend google.protobuf.MessageOptions {
	repeated GoMethodOption gomethod = 78901;
	optional SQLOption gosql = 78902;
}

extend google.protobuf.FieldOptions {
	optional string gojson = 78902;
	optional string gotag = 78904;
}

extend google.protobuf.EnumValueOptions {
	optional string goerror = 78903;
}