// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protox.proto

package protox

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       uint32                 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         uint32                 `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_protox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_protox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_protox_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamp) GetSeconds() uint32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanos() uint32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

type GoMethodOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Return        *string                `protobuf:"bytes,2,opt,name=return,proto3,oneof" json:"return,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoMethodOption) Reset() {
	*x = GoMethodOption{}
	mi := &file_protox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoMethodOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoMethodOption) ProtoMessage() {}

func (x *GoMethodOption) ProtoReflect() protoreflect.Message {
	mi := &file_protox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoMethodOption.ProtoReflect.Descriptor instead.
func (*GoMethodOption) Descriptor() ([]byte, []int) {
	return file_protox_proto_rawDescGZIP(), []int{1}
}

func (x *GoMethodOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoMethodOption) GetReturn() string {
	if x != nil && x.Return != nil {
		return *x.Return
	}
	return ""
}

type SQLOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serializer    *string                `protobuf:"bytes,2,opt,name=serializer,proto3,oneof" json:"serializer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLOption) Reset() {
	*x = SQLOption{}
	mi := &file_protox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLOption) ProtoMessage() {}

func (x *SQLOption) ProtoReflect() protoreflect.Message {
	mi := &file_protox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLOption.ProtoReflect.Descriptor instead.
func (*SQLOption) Descriptor() ([]byte, []int) {
	return file_protox_proto_rawDescGZIP(), []int{2}
}

func (x *SQLOption) GetSerializer() string {
	if x != nil && x.Serializer != nil {
		return *x.Serializer
	}
	return ""
}

type OrmxOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        string                 `protobuf:"bytes,78901,opt,name=column,proto3" json:"column,omitempty"`
	Insert        *bool                  `protobuf:"varint,78902,opt,name=insert,proto3,oneof" json:"insert,omitempty"`
	Select        *bool                  `protobuf:"varint,78903,opt,name=select,proto3,oneof" json:"select,omitempty"`
	Update        *bool                  `protobuf:"varint,78904,opt,name=update,proto3,oneof" json:"update,omitempty"`
	Type          *string                `protobuf:"bytes,78910,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Operate       *string                `protobuf:"bytes,78911,opt,name=operate,proto3,oneof" json:"operate,omitempty"`
	Incr          *int32                 `protobuf:"varint,78912,opt,name=incr,proto3,oneof" json:"incr,omitempty"`
	Desr          *int32                 `protobuf:"varint,78913,opt,name=desr,proto3,oneof" json:"desr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrmxOption) Reset() {
	*x = OrmxOption{}
	mi := &file_protox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrmxOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrmxOption) ProtoMessage() {}

func (x *OrmxOption) ProtoReflect() protoreflect.Message {
	mi := &file_protox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrmxOption.ProtoReflect.Descriptor instead.
func (*OrmxOption) Descriptor() ([]byte, []int) {
	return file_protox_proto_rawDescGZIP(), []int{3}
}

func (x *OrmxOption) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *OrmxOption) GetInsert() bool {
	if x != nil && x.Insert != nil {
		return *x.Insert
	}
	return false
}

func (x *OrmxOption) GetSelect() bool {
	if x != nil && x.Select != nil {
		return *x.Select
	}
	return false
}

func (x *OrmxOption) GetUpdate() bool {
	if x != nil && x.Update != nil {
		return *x.Update
	}
	return false
}

func (x *OrmxOption) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *OrmxOption) GetOperate() string {
	if x != nil && x.Operate != nil {
		return *x.Operate
	}
	return ""
}

func (x *OrmxOption) GetIncr() int32 {
	if x != nil && x.Incr != nil {
		return *x.Incr
	}
	return 0
}

func (x *OrmxOption) GetDesr() int32 {
	if x != nil && x.Desr != nil {
		return *x.Desr
	}
	return 0
}

var file_protox_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*GoMethodOption)(nil),
		Field:         78901,
		Name:          "protox.gomethod",
		Tag:           "bytes,78901,opt,name=gomethod",
		Filename:      "protox.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*SQLOption)(nil),
		Field:         78902,
		Name:          "protox.gosql",
		Tag:           "bytes,78902,opt,name=gosql",
		Filename:      "protox.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         78902,
		Name:          "protox.gojson",
		Tag:           "bytes,78902,opt,name=gojson",
		Filename:      "protox.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*OrmxOption)(nil),
		Field:         78903,
		Name:          "protox.ormx",
		Tag:           "bytes,78903,opt,name=ormx",
		Filename:      "protox.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         78903,
		Name:          "protox.goerror",
		Tag:           "bytes,78903,opt,name=goerror",
		Filename:      "protox.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional protox.GoMethodOption gomethod = 78901;
	E_Gomethod = &file_protox_proto_extTypes[0]
	// optional protox.SQLOption gosql = 78902;
	E_Gosql = &file_protox_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string gojson = 78902;
	E_Gojson = &file_protox_proto_extTypes[2]
	// optional protox.OrmxOption ormx = 78903;
	E_Ormx = &file_protox_proto_extTypes[3]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional string goerror = 78903;
	E_Goerror = &file_protox_proto_extTypes[4]
)

var File_protox_proto protoreflect.FileDescriptor

const file_protox_proto_rawDesc = "" +
	"\n" +
	"\fprotox.proto\x12\x06protox\x1a google/protobuf/descriptor.proto\";\n" +
	"\tTimestamp\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\rR\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\rR\x05nanos\"V\n" +
	"\x0eGoMethodOption\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\x98\x01\x03R\x04name\x12 \n" +
	"\x06return\x18\x02 \x01(\tB\x03\x98\x01\x03H\x00R\x06return\x88\x01\x01B\t\n" +
	"\a_return\"D\n" +
	"\tSQLOption\x12(\n" +
	"\n" +
	"serializer\x18\x02 \x01(\tB\x03\x98\x01\x03H\x00R\n" +
	"serializer\x88\x01\x01B\r\n" +
	"\v_serializer\"\xe5\x02\n" +
	"\n" +
	"OrmxOption\x12\x1d\n" +
	"\x06column\x18\xb5\xe8\x04 \x01(\tB\x03\x98\x01\x04R\x06column\x12\"\n" +
	"\x06insert\x18\xb6\xe8\x04 \x01(\bB\x03\x98\x01\x04H\x00R\x06insert\x88\x01\x01\x12\"\n" +
	"\x06select\x18\xb7\xe8\x04 \x01(\bB\x03\x98\x01\x04H\x01R\x06select\x88\x01\x01\x12\"\n" +
	"\x06update\x18\xb8\xe8\x04 \x01(\bB\x03\x98\x01\x04H\x02R\x06update\x88\x01\x01\x12\x1e\n" +
	"\x04type\x18\xbe\xe8\x04 \x01(\tB\x03\x98\x01\x04H\x03R\x04type\x88\x01\x01\x12$\n" +
	"\aoperate\x18\xbf\xe8\x04 \x01(\tB\x03\x98\x01\x04H\x04R\aoperate\x88\x01\x01\x12\x1e\n" +
	"\x04incr\x18\xc0\xe8\x04 \x01(\x05B\x03\x98\x01\x04H\x05R\x04incr\x88\x01\x01\x12\x1e\n" +
	"\x04desr\x18\xc1\xe8\x04 \x01(\x05B\x03\x98\x01\x04H\x06R\x04desr\x88\x01\x01B\t\n" +
	"\a_insertB\t\n" +
	"\a_selectB\t\n" +
	"\a_updateB\a\n" +
	"\x05_typeB\n" +
	"\n" +
	"\b_operateB\a\n" +
	"\x05_incrB\a\n" +
	"\x05_desr:X\n" +
	"\bgomethod\x12\x1f.google.protobuf.MessageOptions\x18\xb5\xe8\x04 \x01(\v2\x16.protox.GoMethodOptionR\bgomethod\x88\x01\x01:M\n" +
	"\x05gosql\x12\x1f.google.protobuf.MessageOptions\x18\xb6\xe8\x04 \x01(\v2\x11.protox.SQLOptionR\x05gosql\x88\x01\x01::\n" +
	"\x06gojson\x12\x1d.google.protobuf.FieldOptions\x18\xb6\xe8\x04 \x01(\tR\x06gojson\x88\x01\x01:J\n" +
	"\x04ormx\x12\x1d.google.protobuf.FieldOptions\x18\xb7\xe8\x04 \x01(\v2\x12.protox.OrmxOptionR\x04ormx\x88\x01\x01:@\n" +
	"\agoerror\x12!.google.protobuf.EnumValueOptions\x18\xb7\xe8\x04 \x01(\tR\agoerror\x88\x01\x01B\x1cZ\x1agithub.com/cloudfly/protoxb\x06proto3"

var (
	file_protox_proto_rawDescOnce sync.Once
	file_protox_proto_rawDescData []byte
)

func file_protox_proto_rawDescGZIP() []byte {
	file_protox_proto_rawDescOnce.Do(func() {
		file_protox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protox_proto_rawDesc), len(file_protox_proto_rawDesc)))
	})
	return file_protox_proto_rawDescData
}

var file_protox_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protox_proto_goTypes = []any{
	(*Timestamp)(nil),                     // 0: protox.Timestamp
	(*GoMethodOption)(nil),                // 1: protox.GoMethodOption
	(*SQLOption)(nil),                     // 2: protox.SQLOption
	(*OrmxOption)(nil),                    // 3: protox.OrmxOption
	(*descriptorpb.MessageOptions)(nil),   // 4: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 5: google.protobuf.FieldOptions
	(*descriptorpb.EnumValueOptions)(nil), // 6: google.protobuf.EnumValueOptions
}
var file_protox_proto_depIdxs = []int32{
	4, // 0: protox.gomethod:extendee -> google.protobuf.MessageOptions
	4, // 1: protox.gosql:extendee -> google.protobuf.MessageOptions
	5, // 2: protox.gojson:extendee -> google.protobuf.FieldOptions
	5, // 3: protox.ormx:extendee -> google.protobuf.FieldOptions
	6, // 4: protox.goerror:extendee -> google.protobuf.EnumValueOptions
	1, // 5: protox.gomethod:type_name -> protox.GoMethodOption
	2, // 6: protox.gosql:type_name -> protox.SQLOption
	3, // 7: protox.ormx:type_name -> protox.OrmxOption
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	5, // [5:8] is the sub-list for extension type_name
	0, // [0:5] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protox_proto_init() }
func file_protox_proto_init() {
	if File_protox_proto != nil {
		return
	}
	file_protox_proto_msgTypes[1].OneofWrappers = []any{}
	file_protox_proto_msgTypes[2].OneofWrappers = []any{}
	file_protox_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protox_proto_rawDesc), len(file_protox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_protox_proto_goTypes,
		DependencyIndexes: file_protox_proto_depIdxs,
		MessageInfos:      file_protox_proto_msgTypes,
		ExtensionInfos:    file_protox_proto_extTypes,
	}.Build()
	File_protox_proto = out.File
	file_protox_proto_goTypes = nil
	file_protox_proto_depIdxs = nil
}
