syntax = "proto3";

package utils;

import "google/protobuf/any.proto";
import "protox.proto";

option go_package = "github.com/cloudfly/protox/utils";


message Pagination {
	uint32 page = 1;
	uint32 pageSize = 2;
	repeated string order = 3;
}

message Empty {}


message Base {
	string id = 1 [(protox.tag) = 'json:"id" bson:"_id"'];
	string lockSecret = 2 [(protox.tag) = 'json:"-" bson:"lockSecret"'];
	int64 lockExpireAt = 3 [(protox.tag) = 'json:"lockExpireAt" bson:"lockExpireAt"'];
	int64 version = 5 [(protox.tag) = 'json:"version" bson:"version"'];
	int64 createAt = 6 [(protox.tag) = 'json:"createAt" bson:"createAt"'];
	int64 updateAt = 7 [(protox.tag) = 'json:"updateAt" bson:"updateAt"'];
}

message Index {
	string name = 1 [(protox.tag) = 'json:"name"'];
	repeated string fields = 2 [(protox.tag) = 'json:"fields"'];
	bool unique = 3 [(protox.tag) = 'json:"unique"'];
}
